// STUB DATA, NOT LIVE UPSTREAM INTEGRATION.
// 이슈 #43 범위: 실제 Kafka/Flink/Iceberg/Trino/Airflow/Kubernetes API 호출은 여기 없다
// (#41/#42의 어댑터 작업). 이 배열은 계약(스키마) 자체를 지금 검증/테스트하기 위한
// 손으로 작성한 가짜 데이터다 — 실제 배포 버전/헬스가 아니다.
import { serviceSchema, type Service } from "../schema/service.js";

export const services: Service[] = serviceSchema.array().parse([
  {
    id: "svc-trino",
    name: "Trino",
    type: "trino",
    version: "483",
    status: "healthy",
    endpoint: "https://trino.local.beluga.internal",
    capabilities: ["query.execute", "catalog.list", "schema.browse"],
    dependencies: ["svc-iceberg"],
    lastCheckedAt: "2026-09-21T05:50:00.000Z",
    staleAfterMs: 120_000,
  },
  {
    id: "svc-airflow",
    name: "Airflow",
    type: "airflow",
    version: "3.2.0",
    status: "healthy",
    endpoint: "https://airflow.local.beluga.internal",
    capabilities: ["dag.list", "dagrun.list"],
    dependencies: ["svc-trino"],
    lastCheckedAt: "2026-09-21T05:49:00.000Z",
    staleAfterMs: 300_000,
  },
  {
    id: "svc-iceberg",
    name: "Iceberg (Lakekeeper Catalog)",
    type: "iceberg",
    version: "0.9.0",
    status: "healthy",
    endpoint: "https://catalog.local.beluga.internal",
    capabilities: ["catalog.list", "table.metadata"],
    dependencies: ["svc-flink"],
    lastCheckedAt: "2026-09-21T05:48:00.000Z",
    staleAfterMs: 120_000,
  },
  {
    id: "svc-kafka",
    name: "Kafka",
    type: "kafka",
    version: "3.9.1",
    status: "degraded",
    // 브로커 프로토콜만 노출하고 unified HTTPS 도메인 레지스트리(AGENTS.md)에는 없다.
    endpoint: null,
    capabilities: ["topic.list", "topic.describe", "consumer-group.list"],
    dependencies: [],
    lastCheckedAt: "2026-09-21T05:50:00.000Z",
    staleAfterMs: 60_000,
  },
  {
    id: "svc-flink",
    name: "Flink",
    type: "flink",
    version: "2.1.0",
    status: "stale",
    endpoint: null,
    capabilities: ["job.list", "job.metrics"],
    dependencies: ["svc-kafka"],
    // staleAfterMs(60s)를 훨씬 초과한 과거 시각 — status: "stale"과 일관되게 고정한 예시.
    lastCheckedAt: "2026-09-21T04:00:00.000Z",
    staleAfterMs: 60_000,
  },
  {
    id: "svc-kubernetes",
    name: "Kubernetes",
    type: "kubernetes",
    version: null,
    status: "unknown",
    endpoint: null,
    capabilities: ["pod.list", "namespace.list", "event.list"],
    dependencies: [],
    lastCheckedAt: "2026-09-21T05:45:00.000Z",
    staleAfterMs: 120_000,
  },
  {
    id: "svc-observability",
    name: "Observability Stack",
    type: "observability",
    version: null,
    status: "unavailable",
    endpoint: null,
    capabilities: ["metrics.query"],
    dependencies: [],
    lastCheckedAt: "2026-09-21T05:30:00.000Z",
    staleAfterMs: 60_000,
  },
] satisfies Service[]);
